#!/bin/sh

walloptions="--zoom"

case "$1" in
    "C-w")
        while read file; do
            cp "$file" ~/.config/wallpaper
            feh --bg-fill ~/.config/wallpaper
        done
        ;;
    "W")
        while read file; do
            cp "$file" ~/.config/wallpaper
            feh --bg-fill --no-xinerama "$file"
        done
        ;;
    "C-d")
        while read file; do
            rm "$file"
        done
        ;;
esac
