#!/bin/sh

walloptions="--zoom"

case "$1" in
    "C-w")
        while read file; do
            cp "$file" ~/.config/wallpaper
            xwallpaper --zoom ~/.config/wallpaper
        done
        ;;
    "C-d")
        while read file; do
            rm "$file"
        done
        ;;
esac
